/*
 * simple blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	// Warning: Change this to your own fully-qualified import path!
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/ServiceComputing-Project/Server/go"
	t "github.com/ServiceComputing-Project/Server/test"
)

func main() {
	t.DBTestArticle()
	log.Printf("----------Server started----------")
	t.CreateUser()
	t.DBTestArticle()
	t.DBTestComment()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
